# Custom Language File for Launcher Customizer

[ejs.app]
title = "Agnis's Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/fB5wzVPvSt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Agnis's mods"
welcomeDescription = "Agnis's Mods is a series of Minecraft projets made by Agnis. This Launcher will allow you to play and try these projects."
welcomeDescCTA = "You are just a few clicks away from Agnis's Mods."
